sudo: required
services:
    - docker

before_install:
    - docker build -t asmovic100/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run asmovic100/react-test npm run test -- --coverage

after_success:
    - docker build -t asmovic100/multi-client ./client
    - docker build -t asmovic100/multi-nginx ./nginx
    - docker build -t asmovic100/multi-server ./server
    - docker build -t asmovic100/multi-worker ./worker
    #Login to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push asmovic100/multi-client
    - docker push asmovic100/multi-nginx
    - docker push asmovic100/multi-server
    - docker push asmovic100/multi-worker